---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      network:
        - ['private_network', { ip: '33.33.33.133' }]

suites:
  - name: default
    attributes:
      dev_mode: true
    run_list:
      - role[ghost-blog]
